import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'localization_provider.dart';

final appL10nProvider = Provider<Map<String, String>>((ref) {
  final lang = ref.watch(languageProvider);
  return _appTranslations[lang] ?? _appTranslations[AppLanguage.english]!;
});

const _appTranslations = {
  AppLanguage.english: {
    'app_title': 'Numero Shastra',
    'my_cart': 'My Cart',
    'products': 'Products',
    'search_hint': 'Search products...',
    'add_to_cart': 'Add to Cart',
    'items': 'Items',
    'shop_profit': 'Shop Profit on MRP',
    'final_amount': 'Final Amount',
    'add_items': 'Add Items',
    'empty_cart_btn': 'Empty Cart',
    'place_order': 'Place Order',
    'pay_now': 'Pay Now',
    'thank_you': 'Thank You!',
    'order_success': 'Your order has been placed successfully.',
    'continue_shopping': 'Continue Shopping',
    'empty_cart_msg': 'Your cart is empty',
    'go_to_products': 'Go to Products',
    'confirm': 'Confirm',
    'cancel': 'Cancel',
    'place_pending_order_title': 'Place Pending Order?',
    'place_pending_order_msg':
        'You have items in your cart. Do you want to place this order now?',
    'clear_cart_title': 'Empty Cart?',
    'clear_cart_msg': 'Remove all items?',
    'clear_all': 'Clear All',
    'cart_saved_login': 'Please login to continue.',
    'only_authorized_order':
        'Only guest, salesperson, and retailer can place orders.',
    'logout': 'Logout',
    'profile': 'Profile',
    'orders': 'Orders',
    'home': 'Home',
    'welcome_numeroshastra': 'Welcome to Numero Shastra',
    'welcome_user': 'Welcome, {name}',
    'welcome_suffix': 'to Numero Shastra',
    'role': 'Role',
    'purchase_history': 'Purchase History',
    'login': 'Login',
    'select': 'Select',
    'no_products_found': 'No products found',
    'no_matching_products': 'No matching products',
    'error_loading': 'Error loading',
    'no_internet': 'No internet connection. Please check your network.',
    'internet_connected': 'Back online!',
    'internet_disconnected': 'You are offline. Some features may not work.',
    'save_success': 'Saved successfully!',
    'delete_success': 'Deleted successfully!',
    'save_failed': 'Failed to save.',
    'delete_failed': 'Failed to delete.',
    'please_wait': 'Please wait...',
    'role_change_msg': 'Your access permissions have changed. Reloading app...',
    'shop_link_change_msg':
        'Your shop assignments have changed. Reloading app...',
    'edit_name': 'Edit Name',
    'full_name': 'Full Name',
    'save': 'Save',
    'updating': 'Updating...',
    'name_updated_success': 'Name updated successfully!',
    'analysis_unlocked_title': 'Analysis Unlocked!',
    'analysis_unlocked_msg':
        'Your birthdate analysis is now saved and unlocked successfully. You can now explore all the hidden secrets of your birthdate!',
    'view_analysis': 'View Analysis',
    'payment_failed': 'Payment Failed',
    'delete_order_title': 'Delete Order?',
    'delete_order_msg':
        'Are you sure you want to delete this specific analysis record?',
    'delete_success_msg': 'Record deleted successfully.',
    'delete_failed_msg': 'Failed to delete record.',
    'mobile_app_required_title': 'Mobile App Required',
    'mobile_app_required_msg':
        'Payments are currently optimized for our mobile app to ensure the best security. Please use the Android or iOS app to complete your purchase.',
    'got_it': 'Got it',
    'redirecting_payment': 'Redirecting to Payment Gateway...',
    'confirm_purchase_title': 'Confirm Purchase',
    'unlocking_analyses_msg': 'You are unlocking {count} birthdate analysis:',
    'total_amount_label': 'Total Amount',
    'order_failed_msg': 'Failed to place order',
    'delete_entity_title': 'Delete {entity}',
    'delete_entity_msg': 'Are you sure you want to delete this {entity}?',
    'view_entity_title': 'View {entity}',
    'entity_not_found_msg': '{entity} not found',
    'open_in_maps': 'Open in Maps',
    'choose_language_title': 'Choose Language',
    'select_language_subtitle': 'Select your preferred language to continue',
    'default_language_label': 'Default language',
  },
  AppLanguage.marathi: {
    'app_title': 'Numero Shastra',
    'my_cart': ' माझे कार्ट',
    'products': 'प्रोडक्ट्स',
    'search_hint': 'प्रोडक्ट्स शोधा...',
    'add_to_cart': 'कार्टमध्ये टाका',
    'items': 'सामान',
    'shop_profit': 'दुकानाचा नफा (MRP वर)',
    'final_amount': 'एकूण रक्कम',
    'add_items': 'प्रोडक्ट्स वाढवा',
    'empty_cart_btn': 'कार्ट रिकामे करा',
    'place_order': 'ऑर्डर करा',
    'pay_now': 'आता पैसे द्या',
    'thank_you': 'धन्यवाद!',
    'order_success': 'आपली ऑर्डर यशस्वीरीत्या पूर्ण झाली आहे.',
    'continue_shopping': 'खरेदी सुरू ठेवा',
    'empty_cart_msg': 'आपले कार्ट रिकामे आहे',
    'go_to_products': 'प्रोडक्ट्स पहा',
    'confirm': 'ठीक आहे',
    'cancel': 'रद्द करा',
    'place_pending_order_title': 'जुनी ऑर्डर पूर्ण करायची का?',
    'place_pending_order_msg':
        'आपल्या कार्टमध्ये जुने सामान आहे. आता ऑर्डर करायची आहे का?',
    'clear_cart_title': 'कार्ट रिकामे करायचे का?',
    'clear_cart_msg': 'सर्व प्रोडक्ट्स काढून टाका?',
    'clear_all': 'सर्व काढा',
    'cart_saved_login': 'कृपया सुरू ठेवण्यासाठी लॉगिन करा.',
    'only_authorized_order':
        'फक्त गेस्ट, सेल्सपर्सन आणि रिटेलर ऑर्डर करू शकतात.',
    'logout': 'लॉग आउट',
    'profile': 'माझे प्रोफाइल',
    'orders': 'माझी ऑर्डर',
    'home': 'All',
    'welcome_numeroshastra': 'Numero Shastra मध्ये स्वागत आहे',
    'welcome_user': 'स्वागत आहे, {name}',
    'welcome_suffix': 'Numero Shastra मध्ये',
    'role': 'Role',
    'purchase_history': 'जुने ऑर्डर',
    'login': 'लॉगिन करा',
    'select': 'निवडा',
    'no_products_found': 'कोणतेही प्रोडक्ट सापडले नाही',
    'no_matching_products': 'जुळणारे प्रोडक्ट सापडले नाही',
    'error_loading': 'क्षमस्व, लोड होत नाही',
    'no_internet': 'इंटरनेट कनेक्शन नाही. कृपया तुमचे नेटवर्क तपासा.',
    'internet_connected': 'इंटरनेट परत आले!',
    'internet_disconnected': 'तुम्ही ऑफलाइन आहात. काही सुविधा काम करणार नाहीत.',
    'save_success': 'यशस्वीरीत्या सेव्ह झाले!',
    'delete_success': 'यशस्वीरीत्या डिलीट झाले!',
    'save_failed': 'सेव्ह होऊ शकले नाही.',
    'delete_failed': 'डिलीट होऊ शकले नाही.',
    'please_wait': 'कृपया थांबा..',
    'role_change_msg': 'तुमची परवानगी बदलली आहे. अ‍ॅप पुन्हा लोड होत आहे...',
    'shop_link_change_msg':
        'तुमची शॉप असाइनमेंट बदलली आहे. अ‍ॅप पुन्हा लोड होत आहे...',
    'edit_name': 'नाव बदला',
    'full_name': 'पूर्ण नाव',
    'save': 'सेव्ह करा',
    'updating': 'अपडेट होत आहे...',
    'name_updated_success': 'नाव यशस्वीरीत्या बदलले आहे!',
    'analysis_unlocked_title': 'विश्लेषण अनलॉक झाले!',
    'analysis_unlocked_msg':
        'तुमचे जन्मतारीख विश्लेषण आता यशस्वीरीत्या सेव्ह आणि अनलॉक झाले आहे. आता तुम्ही तुमच्या जन्मतारखेचे सर्व छुपे रहस्य शोधू शकता!',
    'view_analysis': 'विश्लेषण पहा',
    'payment_failed': 'पेमेंट अयशस्वी',
    'delete_order_title': 'ऑर्डर डिलीट करायची?',
    'delete_order_msg':
        'तुम्हाला हे विशिष्ट विश्लेषण रेकॉर्ड डिलीट करायचे आहे का?',
    'delete_success_msg': 'रेकॉर्ड यशस्वीरीत्या डिलीट झाले.',
    'delete_failed_msg': 'रेकॉर्ड डिलीट करण्यात अडचण आली.',
    'mobile_app_required_title': 'मोबाईल अ‍ॅप आवश्यक',
    'mobile_app_required_msg':
        'सुरक्षेसाठी पेमेंट सध्या आमच्या मोबाईल अ‍ॅपसाठी ऑप्टिमाइझ केले आहे. कृपया तुमची खरेदी पूर्ण करण्यासाठी अँड्रॉइड किंवा iOS अ‍ॅप वापरा.',
    'got_it': 'समजले',
    'redirecting_payment': 'पेमेंट गेटवेवर रिडायरेक्ट होत आहे...',
    'confirm_purchase_title': 'खरेदीची पुष्टी करा',
    'unlocking_analyses_msg':
        'तुम्ही {count} जन्म तारीख विश्लेषण अनलॉक करत आहात:',
    'total_amount_label': 'एकूण रक्कम',
    'order_failed_msg': 'ऑर्डर देण्यात अडचण आली',
    'delete_entity_title': '{entity} डिलीट करायचे?',
    'delete_entity_msg':
        'तुम्हाला खात्री आहे की तुम्ही हे {entity} डिलीट करू इच्छिता?',
    'view_entity_title': '{entity} पहा',
    'entity_not_found_msg': '{entity} सापडले नाही',
    'open_in_maps': 'मॅपमध्ये उघडा',
    'choose_language_title': 'भाषा निवडा',
    'select_language_subtitle': 'सुरू ठेवण्यासाठी तुमची पसंतीची भाषा निवडा',
    'default_language_label': 'डिफॉल्ट भाषा',
  },
  AppLanguage.hindi: {
    'app_title': 'Numero Shastra',
    'my_cart': 'मेरा कार्ट',
    'products': 'प्रोडक्ट्स',
    'search_hint': 'प्रोडक्ट खोजें...',
    'add_to_cart': 'कार्ट में डालें',
    'items': 'सामान',
    'shop_profit': 'दुकान का मुनाफा (MRP पर)',
    'final_amount': 'कुल रकम',
    'add_items': 'प्रोडक्ट जोड़ें',
    'empty_cart_btn': 'कार्ट खाली करें',
    'place_order': 'ऑर्डर करें',
    'pay_now': 'अभी भुगतान करें',
    'thank_you': 'धन्यवाद!',
    'order_success': 'आपका ऑर्डर सफलतापूर्वक हो गया है।',
    'continue_shopping': 'खरीदारी जारी रखें',
    'empty_cart_msg': 'आपका कार्ट खाली है',
    'go_to_products': 'प्रोडक्ट्स देखें',
    'confirm': 'ठीक है',
    'cancel': 'रद्द करें',
    'place_pending_order_title': 'पुराना ऑर्डर पूरा करें?',
    'place_pending_order_msg':
        'आपके कार्ट में पुराना सामान है। क्या आप अभी ऑर्डर करना चाहते हैं?',
    'clear_cart_title': 'कार्ट खाली करें?',
    'clear_cart_msg': 'सारे प्रोडक्ट हटाएँ?',
    'clear_all': 'सब हटाएँ',
    'cart_saved_login': 'कृपया जारी रखने के लिए लॉगिन करें।',
    'only_authorized_order':
        'केवल गेस्ट, सेल्सपर्सन और रिटेलर ही ऑर्डर कर सकते हैं।',
    'logout': 'लॉग आउट',
    'profile': 'मेरा प्रोफ़ाइल',
    'orders': 'मेरे ऑर्डर',
    'home': 'All',
    'welcome_numeroshastra': 'Numero Shastra में स्वागत है',
    'welcome_user': 'स्वागत है, {name}',
    'welcome_suffix': 'Numero Shastra में',
    'role': 'Role',
    'purchase_history': 'पुराने ऑर्डर',
    'login': 'लॉगिन करें',
    'select': 'चुनें',
    'no_products_found': 'कोई प्रोडक्ट नहीं मिला',
    'no_matching_products': 'मिलता-जुलता प्रोडक्ट नहीं मिला',
    'error_loading': 'क्षमा करें, लोड नहीं हो पाया',
    'no_internet': 'इंटरनेट कनेक्शन नहीं है। कृपया अपना नेटवर्क जांचें।',
    'internet_connected': 'इंटरनेट वापस आ गया!',
    'internet_disconnected': 'आप ऑफलाइन हैं। कुछ सुविधाएँ काम नहीं करेंगी।',
    'save_success': 'सफलतापूर्वक सेव हो गया!',
    'delete_success': 'सफलतापूर्वक डिलीट हो गया!',
    'save_failed': 'सेव नहीं हो पाया।',
    'delete_failed': 'डिलीट नहीं हो पाया।',
    'please_wait': 'कृपया प्रतीक्षा करें...',
    'role_change_msg': 'आपकी अनुमति बदल गई है। ऐप फिर से लोड हो रहा है...',
    'shop_link_change_msg':
        'आपका शॉप असाइनमेंट बदल गया है। ऐप फिर से लोड हो रहा है...',
    'edit_name': 'नाम बदलें',
    'full_name': 'पूरा नाम',
    'save': 'सेव करें',
    'updating': 'अपडेट हो रहा है...',
    'name_updated_success': 'नाम सफलतापूर्वक अपडेट हो गया!',
    'analysis_unlocked_title': 'विश्लेषण अनलॉक हो गया!',
    'analysis_unlocked_msg':
        'आपका जन्मतिथि विश्लेषण अब सफलतापूर्वक सेव और अनलॉक हो गया है। अब आप अपनी जन्मतिथि के सभी छिपे हुए रहस्यों को देख सकते हैं!',
    'view_analysis': 'विश्लेषण देखें',
    'payment_failed': 'भुगतान विफल',
    'delete_order_title': 'ऑर्डर डिलीट करें?',
    'delete_order_msg':
        'क्या आप वाकई इस विशिष्ट विश्लेषण रिकॉर्ड को हटाना चाहते हैं?',
    'delete_success_msg': 'रिकॉर्ड सफलतापूर्वक डिलीट हो गया।',
    'delete_failed_msg': 'रिकॉर्ड डिलीट करने में विफल।',
    'mobile_app_required_title': 'मोबाइल ऐप आवश्यक',
    'mobile_app_required_msg':
        'भुगतान वर्तमान में हमारे मोबाइल ऐप के लिए अनुकूलित हैं। अपनी खरीदारी पूरी करने के लिए कृपया एंड्रॉइड या iOS ऐप का उपयोग करें।',
    'got_it': 'ठीक है',
    'redirecting_payment': 'पेमेंट गेटवे पर रीडायरेक्ट किया जा रहा है...',
    'confirm_purchase_title': 'खरीद की पुष्टि करें',
    'unlocking_analyses_msg': 'आप {count} जन्म तिथि विश्लेषण अनलॉक कर रहे हैं:',
    'total_amount_label': 'कुल राशि',
    'order_failed_msg': 'ऑर्डर देने में विफल',
    'delete_entity_title': '{entity} डिलीट करें?',
    'delete_entity_msg': 'क्या आप वाकई इस {entity} को हटाना चाहते हैं?',
    'view_entity_title': '{entity} देखें',
    'entity_not_found_msg': '{entity} नहीं मिला',
    'open_in_maps': 'मैप में खोलें',
    'choose_language_title': 'भाषा चुनें',
    'select_language_subtitle': 'जारी रखने के लिए अपनी पसंदीदा भाषा चुनें',
    'default_language_label': 'डिफॉल्ट भाषा',
  },
};
