import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'localization_provider.dart';

final birthdateL10nProvider = Provider<Map<String, String>>((ref) {
  final lang = ref.watch(languageProvider);
  return _birthdateTranslations[lang] ??
      _birthdateTranslations[AppLanguage.english]!;
});

const _birthdateTranslations = {
  AppLanguage.english: {
    'birthdate_label': 'Birthdate',
    'age_prefix': 'Your age today is',
    'no_birthdate': 'No Birthdate',
    'years': 'years',
    'months': 'months',
    'days': 'days',
    'birthdate_analysis': 'Birthdate Analysis',
    'personality_number_label': 'Personality Number',
    'life_path_number_label': 'Life Path Number',
    'pinnacle1_number_label': 'Pinnacle 1',
    'pinnacle2_number_label': 'Pinnacle 2',
    'pinnacle3_number_label': 'Pinnacle 3',
    'pinnacle4_number_label': 'Pinnacle 4',
    'pinnacle_base_label': 'Pinnacle Base',
    'absent_numbers_label': 'Missing Numbers',
    'occurrence_label': 'Number Occurrences',
    'number_occurrence_details_label': 'Number Occurrence Details',
    'loshu_planes_label': 'Lo Shu Grid Planes',
    'missing_number_tells_label': 'Missing Number Tells',
    'missing_number_remedies_label': 'Missing Number Remedies',
    'important_points_label': 'Important Points',
    'remedy_values_label': 'Lucky - Unlucky',
    'stock_market_info_label': 'Stock Market Info',
    'personality_details_label': 'Personality Details',
    'testimonials_label': 'Testimonials',
    'life_path_details_label': 'Life Path Details',
    'career_details_label': 'Career Details',
    'boosting_personality_label': 'Boosting Personality',
    'combination_label': 'Personality & Life Path Combination',
    'pinnacle_stage_label': 'Pinnacle stage of Life',
    '1st_pinnacle_stage': '1st Pinnacle stage of Life',
    '2nd_pinnacle_stage': '2nd Pinnacle stage of Life',
    '3rd_pinnacle_stage': '3rd Pinnacle stage of Life',
    '4th_pinnacle_stage': '4th Pinnacle stage of Life',
    'examples_label': 'Examples',
    'description_label': 'Description',
    'personality_label': 'Personality',
    'life_path_label': 'Life Path',
    'appears_times': 'appears {count} times',
    'appears_once': 'appears once',
    'appears_twice': 'appears twice',
    'appears_thrice': 'appears thrice',
    'missing_numbers_from_loshu_grid': 'Missing Numbers (from Lo Shu Grid)',
    'save_birthdate': 'Reveal My Birthdate Secrets',
    'understood': 'Understood',
    'premium_title': 'What you get in Detailed Analysis',
    'premium_feature_1': 'Detailed Lo Shu Grid Analysis',
    'premium_feature_2': 'Career Insights',
    'premium_feature_3': 'Personalized Remedies for Missing Numbers',
    'premium_feature_4': 'Advanced Personality & Strength Mapping',
    'premium_feature_5': 'Life Path & Pinnacle Phase Guidance',
    'premium_feature_6': 'Oracle Voice Guide for Deeper Insights',
    'premium_footer': 'Unlock the full potential of your birthdate today!',
    'read_more': 'Unlock Full Analysis',
    'special_offer': 'Special Offer',
    'add_birthdate': 'Add Birthdate',
    'for_limited_time': '2 or more analysis for',
    'each': 'each',
    'feedback_title': 'Help us improve',
    'feedback_hint': 'Tell us about your overall app experience...',
    'feedback_submit': 'Send Feedback',
    'feedback_success': 'Thank you for your feedback!',
    'feedback_error': 'Failed to send feedback. Please try again.',
    'share_loading': 'Generating shareable analysis...',
    'share_prefix': '✨ Check out my Mystical Analysis! ✨',
    'share_promo': 'Get your own numerology analysis and unlock the secrets of your life path with Numero Shastra! 🔮',
    'share_download': 'Download now on Play Store',
    'share_subject': 'My Numero Shastra Analysis',
    'share_error_msg': 'Failed to share',
    'narrator_intro': 'Hello! I am your Oracle guide. This is your personal birthdate analysis, revealing the mystical patterns of your life.',
    'narrator_age': 'This analysis is based on your current age, which is ',
    'narrator_core': 'First, let\'s look at your core numerology numbers. Your Personality Number represents how others see you, while your Life Path Number reveals your life\'s purpose.',
    'narrator_personality': 'In this section, we analyze your natural character traits and ruling planetary influences.',
    'narrator_loshu': 'The Lo Shu Grid is an ancient tool used to understand your destiny. Here is what your grid reveals.',
    'narrator_planes': 'These planes in your grid represent different life aspects like thought, action, and success.',
    'narrator_remedies': 'To enhance your positive energy, here are your lucky numbers, colors, and days.',
    'narrator_missing_tells': 'When certain numbers are missing from your grid, they indicate specific challenges you might face.',
    'narrator_missing_remedies': 'To balance these missing energies, you can follow these simple remedies.',
    'narrator_occurrence': 'How many times a number repeats in your chart also significantly affects your personality.',
    'narrator_important': 'These are crucial insights specifically tailored to your unique number combinations.',
    'narrator_stock': 'If you are interested in investments, these numbers might influence your financial decisions.',
    'narrator_pinnacle': 'Life is divided into four major stages called Pinnacles. Each stage has a specific influence.',
    'narrator_pinnacle_detail': 'For age range {range}, your pinnacle number is {number}. This tells us that: ',
    'narrator_lifepath': 'This section gives deeper insights into your life\'s long-term journey.',
    'narrator_career': 'Based on your numbers, these career paths might be most fulfilling for you.',
    'narrator_boosting': 'You can further strengthen your personality by following these simple tips.',
    'narrator_combination': 'Finally, we look at how your different numbers interact with each other to create your unique life pattern.',
    'listen': 'Listen',
    'share': 'Share',
  },
  AppLanguage.marathi: {
    'birthdate_label': 'जन्म तारीख',
    'age_prefix': 'तुमचे आजचे वय',
    'no_birthdate': 'जन्म तारीख निवडली नाही',
    'years': 'वर्षे',
    'months': 'महिने',
    'days': 'दिवस',
    'birthdate_analysis': 'जन्म तारीख विश्लेषण',
    'personality_number_label': 'व्यक्तिमत्व क्रमांक',
    'life_path_number_label': 'जीवन पथ क्रमांक',
    'pinnacle1_number_label': 'शिखर १',
    'pinnacle2_number_label': 'शिखर २',
    'pinnacle3_number_label': 'शिखर ३',
    'pinnacle4_number_label': 'शिखर ४',
    'pinnacle_base_label': 'शिखर आधार',
    'absent_numbers_label': 'अनुपस्थित क्रमांक',
    'occurrence_label': 'अंक वारंवारता',
    'number_occurrence_details_label': 'अंक वारंवारता तपशील',
    'loshu_planes_label': 'लो शू ग्रिड प्लेन्स',
    'missing_number_tells_label': 'अनुपस्थित अंक माहिती',
    'missing_number_remedies_label': 'अनुपस्थित अंक उपाय',
    'important_points_label': 'महत्त्वाचे मुद्दे',
    'remedy_values_label': 'भाग्यशाली - अशुभ',
    'stock_market_info_label': 'स्टॉक मार्केट माहिती',
    'personality_details_label': 'व्यक्तिमत्व तपशील',
    'testimonials_label': 'प्रशंसापत्रे',
    'life_path_details_label': 'जीवन पथ तपशील',
    'career_details_label': 'करिअर तपशील',
    'boosting_personality_label': 'व्यक्तिमत्व वाढवणे',
    'combination_label': 'व्यक्तिमत्व आणि जीवन पथ संयोजन',
    'pinnacle_stage_label': 'जीवनाचे शिखर स्टेज',
    '1st_pinnacle_stage': 'जीवनाचे पहिले शिखर स्टेज',
    '2nd_pinnacle_stage': 'जीवनाचे दुसरे शिखर स्टेज',
    '3rd_pinnacle_stage': 'जीवनाचे तिसरे शिखर स्टेज',
    '4th_pinnacle_stage': 'जीवनाचे चौथे शिखर स्टेज',
    'examples_label': 'उदाहरणे',
    'description_label': 'वर्णन',
    'personality_label': 'व्यक्तिमत्व',
    'life_path_label': 'जीवन पथ',
    'appears_times': '{count} वेळा दिसते',
    'appears_once': 'एकदा दिसते',
    'appears_twice': 'दोनदा दिसते',
    'appears_thrice': 'तीनदा दिसते',
    'missing_numbers_from_loshu_grid': 'अनुपस्थित क्रमांक (लो शू ग्रिडपासून)',
    'save_birthdate': 'माझे जन्मदिनाचे रहस्य उलगडा',
    'understood': 'समजले',
    'premium_title': 'तपशीलवार विश्लेषणामध्ये तुम्हाला काय मिळेल',
    'premium_feature_1': 'तपशीलवार लो शू ग्रिड विश्लेषण',
    'premium_feature_2': 'करिअरबद्दल माहिती',
    'premium_feature_3': 'गहाळ अंकांसाठी वैयक्तिक उपाय',
    'premium_feature_4': 'प्रगत व्यक्तिमत्व आणि सामर्थ्य मॅपिंग',
    'premium_feature_5': 'जीवन पथ आणि शिखर टप्प्याचे मार्गदर्शन',
    'premium_feature_6': 'सखोल माहितीसाठी ओरॅकल व्हॉइस मार्गदर्शक',
    'premium_footer': 'आजच तुमच्या जन्मतारखेची पूर्ण क्षमता अनलॉक करा!',
    'read_more': 'पूर्ण विश्लेषण अनलॉक करा',
    'special_offer': 'खास ऑफर',
    'add_birthdate': 'बर्थडेट जोडा',
    'for_limited_time': '१+ विश्लेषणासाठी फक्त',
    'each': 'प्रत्येक',
    'feedback_title': 'आम्हाला सुधारण्यास मदत करा',
    'feedback_hint': 'तुमचा एकूण अ‍ॅप अनुभव आम्हाला सांगा...',
    'feedback_submit': 'फीडबॅक पाठवा',
    'feedback_success': 'तुमच्या फीडबॅकबद्दल धन्यवाद!',
    'feedback_error': 'फीडबॅक पाठवता आला नाही. कृपया पुन्हा प्रयत्न करा.',
    'share_loading': 'शेअर करण्यायोग्य विश्लेषण तयार करत आहे...',
    'share_prefix': '✨ माझे गूढ विश्लेषण पहा! ✨',
    'share_promo': 'तुमचे स्वतःचे अंकशास्त्र विश्लेषण मिळवा आणि न्युमेरो शास्त्र सह तुमच्या जीवन मार्गाचे रहस्य उलगडा! 🔮',
    'share_download': 'आता प्ले स्टोअरवर डाउनलोड करा',
    'share_subject': 'माझे न्युमेरो शास्त्र विश्लेषण',
    'share_error_msg': 'शेअर करण्यात अयशस्वी',
    'narrator_intro': 'नमस्कार! मी तुमचा ओरॅकल मार्गदर्शक आहे. हे तुमचे वैयक्तिक जन्मतारीख विश्लेषण आहे, जे तुमच्या जीवनातील रहस्ये उलगडते.',
    'narrator_age': 'हे विश्लेषण तुमच्या सध्याच्या वयावर आधारित आहे, जे आहे ',
    'narrator_core': 'प्रथम, तुमचे मूळ अंकशास्त्र क्रमांक पाहूया. तुमचा व्यक्तिमत्व क्रमांक इतरांना तुम्ही कसे दिसता हे दर्शवतो, तर तुमचा जीवन पथ क्रमांक तुमच्या जीवनाचा उद्देश दर्शवतो.',
    'narrator_personality': 'या विभागात, आम्ही तुमच्या नैसर्गिक स्वभाव वैशिष्ट्यांचे आणि ग्रहांच्या प्रभावांचे विश्लेषण करतो.',
    'narrator_loshu': 'लो शू ग्रिड हे तुमचे नशीब समजून घेण्याचे एक प्राचीन साधन आहे. तुमचे ग्रिड काय सांगते ते येथे आहे.',
    'narrator_planes': 'तुमच्या ग्रिडमधील हे स्तर विचार, कृती आणि यश यासारख्या जीवनातील विविध पैलूंचे प्रतिनिधित्व करतात.',
    'narrator_remedies': 'तुमची सकारात्मक ऊर्जा वाढवण्यासाठी, तुमचे भाग्यवान क्रमांक, रंग आणि दिवस येथे आहेत.',
    'narrator_missing_tells': 'जेव्हा तुमच्या ग्रिडमध्ये काही विशिष्ट क्रमांक नसतात, तेव्हा ते तुम्हाला कोणत्या आव्हानांना सामोरे जावे लागू शकते हे दर्शवतात.',
    'narrator_missing_remedies': 'या कमतरता संतुलित करण्यासाठी, तुम्ही या सोप्या उपायांचे पालन करू शकता.',
    'narrator_occurrence': 'तुमच्या चार्टमध्ये एखादा अंक किती वेळा येतो, याचा तुमच्या व्यक्तिमत्वावर मोठा परिणाम होतो.',
    'narrator_important': 'हे तुमच्या अंकांच्या संयोजनावर आधारित विशेष तयार केलेले महत्त्वाचे संकेत आहेत.',
    'narrator_stock': 'जर तुम्हाला गुंतवणुकीत रस असेल, तर हे अंक तुमच्या आर्थिक निर्णयांवर परिणाम करू शकतात.',
    'narrator_pinnacle': 'जीवन चार मोठ्या टप्प्यात विभागलेले आहे ज्याला शिखर (Pinnacles) म्हणतात. प्रत्येक टप्प्याचा एक विशिष्ट प्रभाव असतो.',
    'narrator_pinnacle_detail': 'वय {range} साठी, तुमचा शिखर क्रमांक {number} आहे. हे सांगते की: ',
    'narrator_lifepath': 'हा विभाग तुमच्या जीवनाच्या दीर्घकालीन प्रवासाविषयी सखोल माहिती देतो.',
    'narrator_career': 'तुमच्या अंकांनुसार, हे करिअर मार्ग तुमच्यासाठी सर्वात फायदेशीर ठरू शकतात.',
    'narrator_boosting': 'या सोप्या टिप्स फॉलो करून तुम्ही तुमचे व्यक्तिमत्व अधिक मजबूत करू शकता.',
    'narrator_combination': 'शेवटी, तुमचे वेगवेगळे अंक एकमेकांशी कसे संवाद साधतात आणि तुमची अनोखी जीवन पद्धती कशी तयार करतात हे आम्ही पाहतो.',
    'listen': 'ऐका',
    'share': 'शेअर करा',
  },
  AppLanguage.hindi: {
    'birthdate_label': 'जन्म तिथि',
    'age_prefix': 'आपकी आज की उम्र',
    'no_birthdate': 'जन्म तिथि नहीं चुनी गई',
    'years': 'साल',
    'months': 'महीने',
    'days': 'दिन',
    'birthdate_analysis': 'जन्म तिथि विश्लेषण',
    'personality_number_label': 'व्यक्तित्व संख्या',
    'life_path_number_label': 'जीवन पथ संख्या',
    'pinnacle1_number_label': 'शिखर १',
    'pinnacle2_number_label': 'शिखर २',
    'pinnacle3_number_label': 'शिखर ३',
    'pinnacle4_number_label': 'शिखर ४',
    'pinnacle_base_label': 'शिखर आधार',
    'absent_numbers_label': 'अनुपस्थित संख्या',
    'occurrence_label': 'अंकों की आवृत्ति',
    'number_occurrence_details_label': 'अंकों की आवृत्ति विवरण',
    'loshu_planes_label': 'लो शू ग्रिड प्लेन्स',
    'missing_number_tells_label': 'अनुपस्थित अंक जानकारी',
    'missing_number_remedies_label': 'अनुपस्थित अंक उपाय',
    'important_points_label': 'महत्वपूर्ण बिंदु',
    'remedy_values_label': 'भाग्यशाली - अशुभ',
    'stock_market_info_label': 'स्टॉक मार्केट जानकारी',
    'personality_details_label': 'व्यक्तित्व विवरण',
    'testimonials_label': 'प्रशंसापत्र',
    'life_path_details_label': 'जीवन पथ विवरण',
    'career_details_label': 'करियर विवरण',
    'boosting_personality_label': 'व्यक्तित्व बढ़ाना',
    'combination_label': 'व्यक्तित्व और जीवन पथ संयोजन',
    'pinnacle_stage_label': 'जीवन का शिखर चरण',
    '1st_pinnacle_stage': 'जीवन का पहला शिखर चरण',
    '2nd_pinnacle_stage': 'जीवन का दूसरा शिखर चरण',
    '3rd_pinnacle_stage': 'जीवन का तीसरा शिखर चरण',
    '4th_pinnacle_stage': 'जीवन का चौथा शिखर चरण',
    'examples_label': 'उदाहरण',
    'description_label': 'विवरण',
    'personality_label': 'व्यक्तित्व',
    'life_path_label': 'जीवन पथ',
    'appears_times': '{count} बार दिखता है',
    'appears_once': 'एक बार दिखता है',
    'appears_twice': 'दो बार दिखता है',
    'appears_thrice': 'तीन बार दिखता है',
    'missing_numbers_from_loshu_grid': 'अनुपस्थित संख्या (लो शू ग्रिड से)',
    'save_birthdate': 'मेरे जन्मदिन के रहस्य उजागर करें',
    'understood': 'समझ लिया',
    'premium_title': 'विस्तृत विश्लेषण में आपको क्या मिलेगा',
    'premium_feature_1': 'विस्तृत लो शू ग्रिड विश्लेषण',
    'premium_feature_2': 'करियर के बारे में जानकारी',
    'premium_feature_3': 'लुप्त अंकों के लिए व्यक्तिगत उपाय',
    'premium_feature_4': 'उन्नत व्यक्तित्व और शक्ति मैपिंग',
    'premium_feature_5': 'जीवन पथ और शिखर चरण मार्गदर्शन',
    'premium_feature_6': 'गहरी जानकारी के लिए ओरैकल वॉयस गाइड',
    'premium_footer': 'आज ही अपनी जन्मतिथि की पूरी क्षमता को अनलॉक करें!',
    'read_more': 'पूर्ण विश्लेषण अनलॉक करें',
    'special_offer': 'विशेष ऑफर',
    'add_birthdate': 'बर्थडेट जोड़ें',
    'for_limited_time': '१+ विश्लेषण के लिए केवल',
    'each': 'प्रत्येक',
    'feedback_title': 'हमें बेहतर बनाने में मदद करें',
    'feedback_hint': 'हमें अपने समग्र ऐप अनुभव के बारे में बताएं...',
    'feedback_submit': 'प्रतिक्रिया भेजें',
    'feedback_success': 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
    'feedback_error': 'प्रतिक्रिया भेजने में विफल। कृपया पुन: प्रयास करें.',
    'narrator_intro': 'नमस्ते! मैं आपका ओरेकल गाइड हूँ। यह आपका व्यक्तिगत जन्मतिथि विश्लेषण है, जो आपके जीवन के रहस्यमय पैटर्न को प्रकट करता है।',
    'narrator_age': 'यह विश्लेषण आपकी वर्तमान आयु पर आधारित है, जो है ',
    'narrator_core': 'सबसे पहले, आपके मुख्य अंक ज्योतिष नंबरों को देखते हैं। आपका पर्सनैलिटी नंबर यह दर्शाता है कि दूसरे आपको कैसे देखते हैं, जबकि आपका लाइफ पाथ नंबर आपके जीवन के उद्देश्य को प्रकट करता है।',
    'narrator_personality': 'इस खंड में, हम आपके प्राकृतिक व्यक्तित्व लक्षणों और सत्तारूढ़ ग्रहों के प्रभावों का विश्लेषण करते हैं।',
    'narrator_loshu': 'लो शू ग्रिड आपके भाग्य को समझने का एक प्राचीन उपकरण है। आपका ग्रिड क्या प्रकट करता है, यहाँ देखें।',
    'narrator_planes': 'आपके ग्रिड में ये स्तर विचार, क्रिया और सफलता जैसे जीवन के विभिन्न पहलुओं का प्रतिनिधित्व करते हैं।',
    'narrator_remedies': 'अपनी सकारात्मक ऊर्जा को बढ़ाने के लिए, यहाँ आपके भाग्यशाली नंबर, रंग और दिन दिए गए हैं।',
    'narrator_missing_tells': 'जब आपके ग्रिड से कुछ नंबर गायब होते हैं, तो वे उन विशिष्ट चुनौतियों का संकेत देते हैं जिनका आप सामना कर सकते हैं।',
    'narrator_missing_remedies': 'इन गायब ऊर्जाओं को संतुलित करने के लिए, आप इन सरल उपायों का पालन कर सकते हैं।',
    'narrator_occurrence': 'आपके चार्ट में कोई नंबर कितनी बार दोहराया जाता है, यह भी आपके व्यक्तित्व को काफी प्रभावित करता है।',
    'narrator_important': 'ये विशेष रूप से आपके नंबर संयोजनों के लिए तैयार किए गए महत्वपूर्ण अंतर्दृष्टि हैं।',
    'narrator_stock': 'यदि आप निवेश में रुचि रखते हैं, तो ये नंबर आपके वित्तीय निर्णयों को प्रभावित कर सकते हैं।',
    'narrator_pinnacle': 'जीवन को चार प्रमुख चरणों में विभाजित किया गया है जिन्हें शिखर (Pinnacles) कहा जाता है। प्रत्येक चरण का एक विशिष्ट प्रभाव होता है।',
    'narrator_pinnacle_detail': 'आयु {range} के लिए, आपका शिखर नंबर {number} है। यह बताता है कि: ',
    'narrator_lifepath': 'यह खंड आपके जीवन की दीर्घकालिक यात्रा के बारे में गहरी जानकारी देता है।',
    'narrator_career': 'आपके नंबरों के आधार पर, यह करियर पथ आपके लिए सबसे संतोषजनक हो सकता है।',
    'narrator_boosting': 'आप इन सरल युक्तियों का पालन करके अपने व्यक्तित्व को और मजबूत कर सकते हैं।',
    'narrator_combination': 'अंत में, हम देखते हैं कि आपके विभिन्न नंबर एक-दूसरे के साथ कैसे बातचीत करते हैं ताकि आपका अनूठा जीवन पैटर्न बन सके।',
    'share_loading': 'साझा करने योग्य विश्लेषण तैयार किया जा रहा है...',
    'share_prefix': '✨ मेरा रहस्यमय विश्लेषण देखें! ✨',
    'share_promo': 'अपना खुद का अंकशास्त्र विश्लेषण प्राप्त करें और न्युमेरो शास्त्र के साथ अपने जीवन पथ के रहस्यों को अनलॉक करें! 🔮',
    'share_download': 'अभी प्ले स्टोर पर डाउनलोड करें',
    'share_subject': 'मेरा न्युमेरो शास्त्र विश्लेषण',
    'share_error_msg': 'साझा करने में विफल',
    'listen': 'सुनें',
    'share': 'शेयर करें',
  },
};
