import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'localization_provider.dart';

final birthdateL10nProvider = Provider<Map<String, String>>((ref) {
  final lang = ref.watch(languageProvider);
  return _birthdateTranslations[lang] ??
      _birthdateTranslations[AppLanguage.english]!;
});

const _birthdateTranslations = {
  AppLanguage.english: {
    'birthdate_label': 'Birthdate',
    'age_prefix': 'Your age today is',
    'no_birthdate': 'No Birthdate',
    'years': 'years',
    'months': 'months',
    'days': 'days',
    'birthdate_analysis': 'Birthdate Analysis',
    'personality_number_label': 'Personality Number',
    'life_path_number_label': 'Life Path Number',
    'pinnacle1_number_label': 'Pinnacle 1',
    'pinnacle2_number_label': 'Pinnacle 2',
    'pinnacle3_number_label': 'Pinnacle 3',
    'pinnacle4_number_label': 'Pinnacle 4',
    'pinnacle_base_label': 'Pinnacle Base',
    'absent_numbers_label': 'Missing Numbers',
    'occurrence_label': 'Number Occurrences',
    'number_occurrence_details_label': 'Number Occurrence Details',
    'loshu_planes_label': 'Lo Shu Grid Planes',
    'missing_number_tells_label': 'Missing Number Tells',
    'missing_number_remedies_label': 'Missing Number Remedies',
    'important_points_label': 'Important Points',
    'remedy_values_label': 'Lucky - Unlucky',
    'stock_market_info_label': 'Stock Market Info',
    'personality_details_label': 'Personality Details',
    'testimonials_label': 'Testimonials',
    'life_path_details_label': 'Life Path Details',
    'career_details_label': 'Career Details',
    'boosting_personality_label': 'Boosting Personality',
    'combination_label': 'Personality & Life Path Combination',
    'pinnacle_stage_label': 'Pinnacle stage of Life',
    '1st_pinnacle_stage': '1st Pinnacle stage of Life',
    '2nd_pinnacle_stage': '2nd Pinnacle stage of Life',
    '3rd_pinnacle_stage': '3rd Pinnacle stage of Life',
    '4th_pinnacle_stage': '4th Pinnacle stage of Life',
    'examples_label': 'Examples',
    'description_label': 'Description',
    'personality_label': 'Personality',
    'life_path_label': 'Life Path',
    'appears_times': 'appears {count} times',
    'appears_once': 'appears once',
    'appears_twice': 'appears twice',
    'appears_thrice': 'appears thrice',
    'missing_numbers_from_loshu_grid': 'Missing Numbers (from Lo Shu Grid)',
  },
  AppLanguage.marathi: {
    'birthdate_label': 'जन्म तारीख',
    'age_prefix': 'तुमचे आजचे वय',
    'no_birthdate': 'जन्म तारीख निवडली नाही',
    'years': 'वर्षे',
    'months': 'महिने',
    'days': 'दिवस',
    'birthdate_analysis': 'जन्म तारीख विश्लेषण',
    'personality_number_label': 'व्यक्तिमत्व क्रमांक',
    'life_path_number_label': 'जीवन पथ क्रमांक',
    'pinnacle1_number_label': 'शिखर १',
    'pinnacle2_number_label': 'शिखर २',
    'pinnacle3_number_label': 'शिखर ३',
    'pinnacle4_number_label': 'शिखर ४',
    'pinnacle_base_label': 'शिखर आधार',
    'absent_numbers_label': 'अनुपस्थित क्रमांक',
    'occurrence_label': 'अंक वारंवारता',
    'number_occurrence_details_label': 'अंक वारंवारता तपशील',
    'loshu_planes_label': 'लो शू ग्रिड प्लेन्स',
    'missing_number_tells_label': 'अनुपस्थित अंक माहिती',
    'missing_number_remedies_label': 'अनुपस्थित अंक उपाय',
    'important_points_label': 'महत्त्वाचे मुद्दे',
    'remedy_values_label': 'भाग्यशाली - अशुभ',
    'stock_market_info_label': 'स्टॉक मार्केट माहिती',
    'personality_details_label': 'व्यक्तिमत्व तपशील',
    'testimonials_label': 'प्रशंसापत्रे',
    'life_path_details_label': 'जीवन पथ तपशील',
    'career_details_label': 'करिअर तपशील',
    'boosting_personality_label': 'व्यक्तिमत्व वाढवणे',
    'combination_label': 'व्यक्तिमत्व आणि जीवन पथ संयोजन',
    'pinnacle_stage_label': 'जीवनाचे शिखर स्टेज',
    '1st_pinnacle_stage': 'जीवनाचे पहिले शिखर स्टेज',
    '2nd_pinnacle_stage': 'जीवनाचे दुसरे शिखर स्टेज',
    '3rd_pinnacle_stage': 'जीवनाचे तिसरे शिखर स्टेज',
    '4th_pinnacle_stage': 'जीवनाचे चौथे शिखर स्टेज',
    'examples_label': 'उदाहरणे',
    'description_label': 'वर्णन',
    'personality_label': 'व्यक्तिमत्व',
    'life_path_label': 'जीवन पथ',
    'appears_times': '{count} वेळा दिसते',
    'appears_once': 'एकदा दिसते',
    'appears_twice': 'दोनदा दिसते',
    'appears_thrice': 'तीनदा दिसते',
    'missing_numbers_from_loshu_grid': 'अनुपस्थित क्रमांक (लो शू ग्रिडपासून)',
  },
  AppLanguage.hindi: {
    'birthdate_label': 'जन्म तिथि',
    'age_prefix': 'आपकी आज की उम्र',
    'no_birthdate': 'जन्म तिथि नहीं चुनी गई',
    'years': 'साल',
    'months': 'महीने',
    'days': 'दिन',
    'birthdate_analysis': 'जन्म तिथि विश्लेषण',
    'personality_number_label': 'व्यक्तित्व संख्या',
    'life_path_number_label': 'जीवन पथ संख्या',
    'pinnacle1_number_label': 'शिखर १',
    'pinnacle2_number_label': 'शिखर २',
    'pinnacle3_number_label': 'शिखर ३',
    'pinnacle4_number_label': 'शिखर ४',
    'pinnacle_base_label': 'शिखर आधार',
    'absent_numbers_label': 'अनुपस्थित संख्या',
    'occurrence_label': 'अंकों की आवृत्ति',
    'number_occurrence_details_label': 'अंकों की आवृत्ति विवरण',
    'loshu_planes_label': 'लो शू ग्रिड प्लेन्स',
    'missing_number_tells_label': 'अनुपस्थित अंक जानकारी',
    'missing_number_remedies_label': 'अनुपस्थित अंक उपाय',
    'important_points_label': 'महत्वपूर्ण बिंदु',
    'remedy_values_label': 'भाग्यशाली - अशुभ',
    'stock_market_info_label': 'स्टॉक मार्केट जानकारी',
    'personality_details_label': 'व्यक्तित्व विवरण',
    'testimonials_label': 'प्रशंसापत्र',
    'life_path_details_label': 'जीवन पथ विवरण',
    'career_details_label': 'करियर विवरण',
    'boosting_personality_label': 'व्यक्तित्व बढ़ाना',
    'combination_label': 'व्यक्तित्व और जीवन पथ संयोजन',
    'pinnacle_stage_label': 'जीवन का शिखर चरण',
    '1st_pinnacle_stage': 'जीवन का पहला शिखर चरण',
    '2nd_pinnacle_stage': 'जीवन का दूसरा शिखर चरण',
    '3rd_pinnacle_stage': 'जीवन का तीसरा शिखर चरण',
    '4th_pinnacle_stage': 'जीवन का चौथा शिखर चरण',
    'examples_label': 'उदाहरण',
    'description_label': 'विवरण',
    'personality_label': 'व्यक्तित्व',
    'life_path_label': 'जीवन पथ',
    'appears_times': '{count} बार दिखता है',
    'appears_once': 'एक बार दिखता है',
    'appears_twice': 'दो बार दिखता है',
    'appears_thrice': 'तीन बार दिखता है',
    'missing_numbers_from_loshu_grid': 'अनुपस्थित संख्या (लो शू ग्रिड से)',
  },
};
